### PR TITLE
Add Base62 encoding + fix misc naming/typos

### PR DESCRIPTION
**Pull request by lukaskuzmiak**
This PR adds support for Base62 in a `b62` unit (inherited from `base`).

On top of that it fixes/adds a few small things:

- Base58 and Base62 alphabets added to `base.py`
- the class in `test_b58.py` used to be called `TestB32` (copy-paste/typo?) - renamed it to `TestBase58`
- while at it I also renamed `TestB32` to `TestBase32` so all the `TestBaseXY` classes are named consistently (there are others named like that)

### CODE REVIEW

**Comment by huettenhain** [comment]
Nice, thank you for the contribution! It looks like one line has a trailing whitespace, that should be an easy fix. Happy to merge this when the tests go green :-).

**Comment by lukaskuzmiak** [comment]
download
oops, my bad, removed it.

**Comment by huettenhain** [comment]
Oh no don't worry about it, I am actually kinda psyched that the whole CICD thing is working now =)

**Comment by huettenhain** [comment]
Terrific! Thanks again for your contribution!

**Comment by huettenhain** [comment]
New version was released btw so this is now actually live! Thanks again!

**Pull request merged**
