### PR TITLE
Add support for script.bin bytecode extraction. Fixes #62

### LINKED ISSUE #62: Add xtnsis option to extract raw NSIS script bytecode
As per #61, it might be useful to have `xtnsis` provide a synthetic file that represents the setup script bytecode.

### PR DESCRIPTION
**Pull request by utkonos**
Hopefully I didn't do anything naughty.

### CODE REVIEW

**Comment by huettenhain** [comment]
Actually, I thought I already fixed #62 in 024c17120fc7808e83f44729c1b062db0ebd5f0c 😅. If you want the whole header on top of the opcodes and the strings, that can be done more easily by extracting an item with the following data:
```
arc.header.get_data()
```
I.e. you wouldn't have to change more than one line. I am hesitant to implement it as I don't see the use case right now; maybe you can elaborate on that.

**Comment by utkonos** [comment]
@huettenhain The way that I did it results in the correct setup.bin being returned, but I just changed it to how you recommend here and the result is wrong. The setup.bin produced by reverting all my changes and then just adding this:
image

Produces this on the left which is missing bytes at the end from the actual script.bin:

image

As for justification for why I want this data as is: I am looking to have the same capability that is provided by the tool TotalCommander which is listed on NSIS's wiki about decompiling NSIS:
https://nsis.sourceforge.io/Can_I_decompile_an_existing_installer%3F#:~:text=The%20decompression%20plug%2Din%20InstallExplorer%20InstExpl.wcx%20is%20also%20available%20for%20TotalCommander.%20Beside%20the%20files%20it%27ll%20create%20the%20file%20%27script.bin%27%20compiled%20scriptcode.For%20use%20without%20the%20TotalCommander%20the%20Universal%20Extractor%20is%20a%20good%20option.

That is part 1 of why. Part 2: the purpose of using this file is to write detections on the script.bin bytecode. The decompiled script is neat, but I want to attack the ground truth.

**Comment by huettenhain** [comment]
Gotcha, makes sense to me. As to why `.get_data()` doesn't work as expected here; I have a few ideas why it might not, but I'll have to check.

**Comment by huettenhain** [comment]
Ok, so it looks like I am not parsing the entire header; there are a few bytes at the end that do belong to the NSIS header but which are never consumed by the parser. As a result, they don't occur in the `.get_data()` result. I just pushed e17ed51ff68953aeae97e3bc7086f596f43f46db which should do what you want, i.e. it does extract the full decompressed header data. I'll deny this PR and push out a new version ASAP, I hope that's in your best interest.

**Comment by utkonos** [comment]
Sounds great! Thanks!

**Comment by huettenhain** [comment]
[Releasing now](https://github.com/binref/refinery/actions/runs/11927851619) as 0.7.8.

**Pull request closed without merging**
