### PR TITLE
Unit to calculate Chrome extension ID based off of their public key

### PR DESCRIPTION
**Pull request by larsborn**
The public key of a Chrome extension is recorded in its `manifest.json` under `key`. For a Google Chromecast extension I have installed locally, this PR allows to do the following:

```
$ emit "%APPDATA\Local\Google\Chrome\User Data\Default\Extensions\pkedcjkdefgpdelpbcmbmeomcjbeemfm\9021.222.0.0_0\manifest.json" | xtjson key | b64 | crxid
pkedcjkdefgpdelpbcmbmeomcjbeemfm
```

### CODE REVIEW

**Comment by huettenhain** [comment]
This unit is equivalent to the following pipeline:
```
emit manifest.json | xtjson key | b64 | sha256 -t | snip :32 | chop 1 | pack 16 | add a
```
I am reluctant to add a unit for something that is arguably a little exotic when its functionality can already be reproduced with existing units. Do you think this would be sufficient for your needs, i.e. maybe replacing your local unit with the above pipeline?

**Comment by larsborn** [comment]
I don't really have needs here. Just wrote a Python script that is able to extract the extension id from the public key and thought it might be useful to others.

**Comment by huettenhain** [comment]
That is a noble thought, but I think I deem this out of scope. My reasons are as follows:

1. The functionality is reproducible with a single pipeline.
2. You as the author do not actually have any requirement / use case to see this included in refinery.
3. There is no obvious malware triage use case that I am aware of.

I realize that I made the mistake to specify _how_ to contribute in [CONTRIBUTING](https://github.com/binref/refinery/blob/master/CONTRIBUTING.md), but not _what_ to contribute. I will give this some thought and try to formulate better guidelines.

**Comment by larsborn** [comment]
No problem.

I also misunderstood your question: I personally don't have a use case for this unit but there certainly exist use cases in the context of malware triage. I'll document one just in case someone stumbles across this: Let's say you are analyzing a (potentially malicious) Chrome extension and would like to determine its directory on impacted systems (say, for detection or hunting purposes). Since you are analyzing the extension, you have the manifest and hence the public key. You can use the technique documented in this PR to determine the extension id based off of that public key. And the extension id in turns determines the sub directory under APPDATA.

**Pull request closed without merging**
