### PR TITLE
Add SingleFileExtractor Port to BinRef

### PR DESCRIPTION
**Pull request by alphillips-lab**
Hello!

I would like to add support for extracting .NET Bundles:
[https://learn.microsoft.com/en-us/dotnet/core/deploying/single-file/overview](https://learn.microsoft.com/en-us/dotnet/core/deploying/single-file/overview)

The test files originate from the same repo that I ported:
[https://github.com/Droppers/SingleFileExtractor/tree/main](https://github.com/Droppers/SingleFileExtractor/tree/main)

Let me know if you nee anything else, and of course if you need to make the code prettier please do so and I'll take note for the next unit =]

### CODE REVIEW

**Comment by jhhcs** [comment]
Could you try rebasing your branch to refinery's master branch? I have made some changes to the GH actions template and I am _hoping_ this should make malshare samples work again.

**Comment by alphillips-lab** [comment]
Hmm, still looks like tests are failing because it's unable to download the files

**Comment by jhhcs** [comment]
Ok, looks like I failed to fix the malshare integration. I will fix this another time. I'll merge this tonight.

**Comment by jhhcs** [comment]
Merged! Thank you for your contribution. I will try to fix the tests, but should I fail I'll just have to upload these huge files to the test data repo.

**Pull request merged**
